services:
  server:
    build:
      target: development
    volumes:
      - uploads_data:/app/uploads
    environment:
      PORT: 4000
    ports:
      - "4000:4000"

  client:
    build:
      target: development
    volumes:
      - ./client/src:/app/src
      - ./client/index.html:/app/index.html
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:4000
